# Full build setup off main, with ~docsOnly commit filter to run just mvn_site then docs.
name: Default CI

on:
  push:
    branches: [ "main", "temp/*" ]
  pull_request:
    branches: [ "main", "temp/*" ]

env:
  MAVEN_CLI_OPTS: &MAVEN_CLI_OPTS "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # -Dmaven.repo.local=.m2/repository not needed on github, seems ~/.m2 is supported / expected
  MAVEN_OPTS_8: &MAVEN_OPTS_8 "-ea -XX:+IgnoreUnrecognizedVMOptions -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_OPTS_21: &MAVEN_OPTS_21 "-ea -XX:+IgnoreUnrecognizedVMOptions -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/sun.nio.cs=ALL-UNNAMED --add-opens java.base/sun.security.action=ALL-UNNAMED --add-opens java.base/sun.util.calendar=ALL-UNNAMED"

jobs:

  testBuilds_2_12_18_and_13_5:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: test
      theMatrix: |
        {
          "profile": [ "Spark350" ],
          "scala": [ "scala_2.12.18", "scala_2.13.5"]
        }
      jdk: 11
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_8
    secrets: inherit

  noTestBuilds_2_12_18_dbr:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: -DskipTests
      theMatrix: |
        {
          "profile": [ "14.3.dbr", "15.4.dbr" ],
          "scala": [ "scala_2.12.18" ]
        }
      jdk: 11
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_8
    secrets: inherit

  testBuilds_2_13_12:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: test
      theMatrix: |
        {
          "profile": [ "Spark4" ],
          "scala": [ "scala_2.13.12" ]
        }
      sparkVersion: 3.5.5
      hadoopVersion: 3
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  noTestBuilds_2_13_12_dbr:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: -DskipTests
      theMatrix: |
        {
          "profile": [ "17.3.dbr" ],
          "scala": [ "scala_2.13.12" ]
        }
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  testBuilds_2_13_18:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: test
      theMatrix: |
        {
          "profile": [ "Spark41", "Spark42" ],
          "scala": [ "scala_2.13.18" ]
        }
      sparkVersion: 3.5.5
      hadoopVersion: 3
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  noTestBuilds_2_12_18_and_13_5:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: test
      theMatrix: |
        {
          "profile": [ "16.4.dbr"  ],
          "scala": [ "scala_2.12.18", "scala_2.13.5" ]
        }
    secrets: inherit

  noTestBuilds_2_13_18_dbr:
    uses: sparkutils/building/.github/workflows/run_build.yml@main
    with:
      testString: -DskipTests
      theMatrix: |
        {
          "profile": [ "18.3.dbr" ],
          "scala": [ "scala_2.13.18" ]
        }
      sparkVersion: 3.5.5
      hadoopVersion: 3
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  publish_2_12_18:
    needs: [testBuilds_2_12_18]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "14.3.dbr", "15.4.dbr" ],
          "scala": [ "scala_2.12.18" ]
        }
      jdk: 11
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_8
    secrets: inherit

  publish_2_13_12:
    needs: [ testBuilds_2_13_12, noTestBuilds_2_13_12_dbr ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "17.3.dbr", "Spark4" ],
          "scala": [ "scala_2.13.12" ]
        }
      sparkVersion: 3.5.5
      hadoopVersion: 3
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit

  publish_2_12_18_and_13_5:
    needs: [testBuilds_2_12_18_and_13_5, noTestBuilds_2_12_18_and_13_5]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "Spark350", "16.4.dbr" ],
          "scala": [ "scala_2.12.18", "scala_2.13.5" ]
        }
    secrets: inherit

  publish_2_13_18:
    needs: [ testBuilds_2_13_18, noTestBuilds_2_13_18_dbr ]
    uses: sparkutils/building/.github/workflows/publish_build.yml@main
    with:
      theMatrix: |
        {
          "profile": [ "18.3.dbr", "Spark41", "Spark42" ],
          "scala": [ "scala_2.13.18" ]
        }
      sparkVersion: 3.5.5
      hadoopVersion: 3
      jdk: 21
      mvnCliOpts: *MAVEN_CLI_OPTS
      mvnOpts: *MAVEN_OPTS_21
    secrets: inherit
